# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "C:\\Users\\total\\OneDrive\\Documents\\College Stuff\\Metro Stuff\\Fall 2024\\Senior Experience\\Senior_project_repo\\beatbank-senior-project\\beatbank\\src-tauri\\migrations"
