name: 'Publish Release'
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.10.0
      
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      # Install build tools
      - name: Install Visual Studio components
        run: |
          choco install visualstudio2022-workload-vctools -y
          
      # Install Rust
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      # Cache Rust dependencies
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Cache pnpm dependencies
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\AppData\Local\pnpm\store\v3
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
          
      - name: install frontend dependencies
        run: pnpm install

      - name: Set environment variables
        run: |
          echo "SQLITE3_STATIC_LIB=1" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "SQLITE3_NO_PKG_CONFIG=1" | Out-File -FilePath $env:GITHUB_ENV -Append
          
      # Debug information
      - name: Print debug information
        run: |
          rustc --version
          cargo --version
          echo "Environment variables:"
          Get-ChildItem env:

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQLITE3_STATIC_LIB: 1
          SQLITE3_NO_PKG_CONFIG: 1
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ''