name: 'Publish Release'
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm' # Enable Node modules caching
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.10.0
          
      # Cache vcpkg
      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            vcpkg
            C:\Users\runneradmin\AppData\Local\vcpkg\archives
            C:\Users\runneradmin\AppData\Local\Microsoft\vcpkg
          key: ${{ runner.os }}-vcpkg-sqlite3
          
      # Cache Rust dependencies
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
          
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      # Install SQLite only if not cached
      - name: Install SQLite (Windows)
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install sqlite3:x64-windows-static
          .\vcpkg\vcpkg integrate install
          
      # Set VCPKG_ROOT environment variable
      - name: Set VCPKG_ROOT
        run: echo "VCPKG_ROOT=$env:GITHUB_WORKSPACE\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Append

      # Cache pnpm dependencies - fixed version
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\AppData\Local\pnpm\store\v3
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
          
      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ''